### PR TITLE
adds aws-publish task for deploying to S3

### PR DESCRIPTION
**Pull request by bradoyler**
For deploying to AWS S3 😸  #246 
cc: @nsonnad @yanofsky

Instructions:
1. `$ cp config.json.example config.json`
2. populate `config.json` file with your S3 options/creds.
3. `$ gulp publish`

console output:
```
[21:21:52] Using gulpfile ~/projects/Chartbuilder/gulpfile.js
[21:21:52] Starting 'publish'...
[21:21:55] [create] cdnassets/chartbuilder/index.html
[21:21:56] [create] cdnassets/chartbuilder/css/main.css
[21:21:59] [create] cdnassets/chartbuilder/js/main.js
[21:21:59] Finished 'publish' after 6.09 s
```

### CODE REVIEW

**Comment by bradoyler** [comment]
@yanofsky Any objections?

**Comment by nsonnad** [comment]
Thanks @bradoyler! One thing, shouldn't the publish task require the `build` task to be completed first?  Eg

```gulp.task('publish', ['build'], function() { ... })```

**Comment by bradoyler** [comment]
That's prolly a good idea. Although I always run build first anyway.

**Comment by bradoyler** [comment]
@nsonnad cool to merge now? Then I'll get cracking on #165 😈

**Comment by nsonnad** [comment]
Hey Brad, thanks. I made a couple minor changes here https://github.com/Quartz/Chartbuilder/pull/252 (sorry to create a new PR, but github won't let me edit your filez)

* moved/renamed `gulp/aws-config.json` -- was a bit confusing to have multiple `config` files.
* added an npm script so that you can `npm run aws` and don't need global gulp
* added some docs.

Can you verify that that is all good, and if so, we can merge it in. Thanks again!

**Comment by bradoyler** [comment]
close in favor of #252

**Pull request closed without merging**
